/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "stm32f030x8.h"
#include "sct.h"

int main(void)
{
	sct_init();
	sct_led(0x7A5C36DE);

	for( volatile uint32_t j = 0; j <5000000; j++){}    //busy waiting loop

		/* Loop forever */
		for(;;)
		{
			for (uint16_t i = 0; i < 1000; i = i + 111) {
				sct_value(i);
				for( volatile uint32_t j = 0; j <500000; j++){}    //busy waiting loop
			}
		}
}




